# Generated by Django 4.2.7 on 2025-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='imagenes/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
