# Generated by Django 4.2.7 on 2025-04-01 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('imagen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenmedica',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
            preserve_default=False,
        ),
    ]
